version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: sh -c "npm run serve"
    ports:
      - '8080:8080'
    working_dir: /app
    networks:
      - app-network
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    command: sh -c "npm install && npm run start"
    ports:
      - '3001:3001'
    working_dir: /app
    volumes:
      - ./server:/app # Look at the server directory and copy everything into the app folder in the container
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is

networks:
    app-network:
        driver: bridge 